name: Update YouTube Stream

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Extract stream
        run: |
          yt-dlp -g https://www.youtube.com/live/2lJZPT6OljI > stream.txt || echo ""

      - name: Commit update
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-action"
          git add stream.txt
          git commit -m "auto update stream" || echo "no changes"
          git push